apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: meksonbravo/auth
        env:
          - name: JWT_KEY
            valueFrom:
              secretKeyRef: 
                name: jwt-secret-key
                key: JWT_KEY 
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
  - port: 4000
    targetPort: 4000
    name: auth
    protocol: TCP
